import Foundation
import SQLite3

/// Where a drafted reply currently stands.
public enum DraftStatus: String, Sendable, Codable {
    case pending
    case drafting
    case ready
    case failed
    case skippedNewsletter = "skipped_newsletter"
}

/// Where a detected candidate message stands in the Draft-Modus pipeline —
/// the `draft_jobs` table's `state` column. `pending` -> `classifying` ->
/// {`newsletterSkipped` | `autoGenerated` (terminal) | `eligible`} ->
/// `drafting` -> {`drafted` (terminal) | `failed` (retryable with backoff)}.
public enum DraftJobState: String, Sendable, Codable, Equatable {
    case pending
    case classifying
    /// Terminal: `NewsletterClassifier.classify` returned `.newsletter`.
    case newsletterSkipped = "newsletter_skipped"
    /// Terminal: `NewsletterClassifier.isAutoGenerated` matched (RFC 3834
    /// anti-mail-loop gate) — a distinct bucket from `newsletterSkipped` so
    /// Settings can show *why* a message never got a draft.
    case autoGenerated = "auto_generated"
    case eligible
    case drafting
    /// Terminal: a draft was generated and stored.
    case drafted
    /// Retryable: classification or drafting failed (transient LLM error,
    /// vanished source file, empty draft, ...). Eligible for backoff-gated
    /// retry until `attempts` reaches the configured maximum, at which point
    /// it becomes effectively terminal (see `DraftStore.pruneJobs`).
    case failed
}

/// One row of the Draft-Modus job queue (`draft_jobs`).
public struct DraftJob: Sendable, Equatable {
    public var sourceID: Int64
    /// Set once classification has parsed the source file; nil while still
    /// `pending` (the fast envelope-index check doesn't parse the file).
    public var messageID: String?
    public var state: DraftJobState
    public var attempts: Int
    public var lastError: String?
    /// Unix seconds when this candidate was first detected — the SLA clock start.
    public var detectedAt: Int64
    public var updatedAt: Int64

    public init(sourceID: Int64, messageID: String?, state: DraftJobState, attempts: Int,
               lastError: String?, detectedAt: Int64, updatedAt: Int64) {
        self.sourceID = sourceID
        self.messageID = messageID
        self.state = state
        self.attempts = attempts
        self.lastError = lastError
        self.detectedAt = detectedAt
        self.updatedAt = updatedAt
    }
}

public struct DraftRecord: Sendable, Equatable {
    public var pk: Int64
    public var threadID: String
    public var latestMessageID: String
    public var sender: String
    public var subject: String
    public var draftText: String
    public var generatedAt: Int64
    public var status: DraftStatus

    public init(pk: Int64, threadID: String, latestMessageID: String, sender: String, subject: String,
               draftText: String, generatedAt: Int64, status: DraftStatus) {
        self.pk = pk
        self.threadID = threadID
        self.latestMessageID = latestMessageID
        self.sender = sender
        self.subject = subject
        self.draftText = draftText
        self.generatedAt = generatedAt
        self.status = status
    }
}

private let SQLITE_TRANSIENT = unsafeBitCast(-1, to: sqlite3_destructor_type.self)

/// The local database for Draft-Modus (`drafts.db`), physically decoupled
/// from `askmail.db` (`SQLiteStore`): deleting or rebuilding one never
/// touches the other, and drafted content is never commingled with the
/// read-only mail index. Locked down the same way (`FileHardening`).
///
/// `draft_jobs` and `style_profiles` are schema-only in Phase 1 — a later
/// phase's `DraftEngine`/`StyleLearner` are their only writers.
public final class DraftStore {
    private let db: OpaquePointer
    private let lock = NSLock()

    public init(path: String) throws {
        var handle: OpaquePointer?
        guard sqlite3_open(path, &handle) == SQLITE_OK, let opened = handle else {
            let message = handle.map { String(cString: sqlite3_errmsg($0)) } ?? "unknown"
            if let h = handle { sqlite3_close(h) }
            throw StoreError.openFailed(message)
        }
        db = opened
        try execute("PRAGMA journal_mode=WAL")
        try execute("PRAGMA busy_timeout=5000")
        try migrate()
        if path != ":memory:" {
            FileHardening.lockDown(fileURL: URL(fileURLWithPath: path))
        }
    }

    public static func inMemory() throws -> DraftStore {
        try DraftStore(path: ":memory:")
    }

    deinit {
        sqlite3_close(db)
    }

    // MARK: Schema

    private func migrate() throws {
        try execute("""
        CREATE TABLE IF NOT EXISTS drafts(
          pk INTEGER PRIMARY KEY,
          thread_id TEXT NOT NULL,
          latest_message_id TEXT NOT NULL,
          sender TEXT NOT NULL,
          subject TEXT NOT NULL,
          draft_text TEXT NOT NULL,
          generated_at INTEGER NOT NULL,
          status TEXT NOT NULL
        );
        """)
        try execute("CREATE INDEX IF NOT EXISTS idx_drafts_thread ON drafts(thread_id);")
        try execute("""
        CREATE TABLE IF NOT EXISTS draft_jobs(
          source_id INTEGER PRIMARY KEY,
          message_id TEXT,
          state TEXT NOT NULL,
          attempts INTEGER NOT NULL DEFAULT 0,
          last_error TEXT,
          detected_at INTEGER NOT NULL,
          updated_at INTEGER NOT NULL
        );
        """)
        try execute("""
        CREATE TABLE IF NOT EXISTS style_profiles(
          scope TEXT PRIMARY KEY,
          profile_text TEXT NOT NULL,
          sample_count INTEGER NOT NULL,
          updated_at INTEGER NOT NULL
        );
        """)
        try execute("""
        CREATE TABLE IF NOT EXISTS meta(
          key TEXT PRIMARY KEY,
          value TEXT NOT NULL
        );
        """)
    }

    // MARK: Drafts

    @discardableResult
    public func insertDraft(threadID: String, latestMessageID: String, sender: String, subject: String,
                            draftText: String, generatedAt: Int64, status: DraftStatus) throws -> Int64 {
        lock.lock(); defer { lock.unlock() }
        try run("""
        INSERT INTO drafts(thread_id, latest_message_id, sender, subject, draft_text, generated_at, status)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """) { statement in
            bind(statement, 1, threadID)
            bind(statement, 2, latestMessageID)
            bind(statement, 3, sender)
            bind(statement, 4, subject)
            bind(statement, 5, draftText)
            sqlite3_bind_int64(statement, 6, generatedAt)
            bind(statement, 7, status.rawValue)
        }
        return sqlite3_last_insert_rowid(db)
    }

    /// The most recently generated draft for a thread, if any (a thread may
    /// have several rows if the user regenerated — a later phase's concern).
    public func latestDraft(threadID: String) throws -> DraftRecord? {
        lock.lock(); defer { lock.unlock() }
        var result: DraftRecord?
        try query("""
        SELECT pk, thread_id, latest_message_id, sender, subject, draft_text, generated_at, status
        FROM drafts WHERE thread_id = ? ORDER BY generated_at DESC LIMIT 1
        """) { statement in
            bind(statement, 1, threadID)
        } row: { statement in
            result = DraftRecord(
                pk: sqlite3_column_int64(statement, 0),
                threadID: column(statement, 1),
                latestMessageID: column(statement, 2),
                sender: column(statement, 3),
                subject: column(statement, 4),
                draftText: column(statement, 5),
                generatedAt: sqlite3_column_int64(statement, 6),
                status: DraftStatus(rawValue: column(statement, 7)) ?? .pending
            )
        }
        return result
    }

    // MARK: Job queue (Draft-Modus §7 orchestration)

    /// Enqueues a newly-detected candidate for classification. `INSERT OR
    /// IGNORE` on the `source_id` primary key: a candidate re-detected before
    /// it's been processed (e.g. two overlapping ticks) must never reset an
    /// in-flight job's `state`/`attempts`.
    public func enqueueJob(sourceID: Int64, messageID: String?, detectedAt: Int64) throws {
        lock.lock(); defer { lock.unlock() }
        try run("""
        INSERT OR IGNORE INTO draft_jobs(source_id, message_id, state, attempts, last_error, detected_at, updated_at)
        VALUES (?, ?, 'pending', 0, NULL, ?, ?)
        """) { statement in
            sqlite3_bind_int64(statement, 1, sourceID)
            bindOptional(statement, 2, messageID)
            sqlite3_bind_int64(statement, 3, detectedAt)
            sqlite3_bind_int64(statement, 4, detectedAt)
        }
    }

    public func job(sourceID: Int64) throws -> DraftJob? {
        lock.lock(); defer { lock.unlock() }
        var result: DraftJob?
        try query("""
        SELECT source_id, message_id, state, attempts, last_error, detected_at, updated_at
        FROM draft_jobs WHERE source_id = ?
        """) { statement in
            sqlite3_bind_int64(statement, 1, sourceID)
        } row: { statement in
            result = Self.job(from: statement)
        }
        return result
    }

    /// Jobs in any of `states`, oldest-detected first. Used for both the
    /// `pending` classify queue and the `eligible`/`failed` draft queue.
    public func jobs(in states: [DraftJobState], limit: Int? = nil) throws -> [DraftJob] {
        guard !states.isEmpty else { return [] }
        lock.lock(); defer { lock.unlock() }
        let placeholders = Array(repeating: "?", count: states.count).joined(separator: ",")
        let limitClause = limit.map { " LIMIT \($0)" } ?? ""
        var results: [DraftJob] = []
        try query("""
        SELECT source_id, message_id, state, attempts, last_error, detected_at, updated_at
        FROM draft_jobs WHERE state IN (\(placeholders)) ORDER BY detected_at ASC\(limitClause)
        """) { statement in
            for (index, state) in states.enumerated() {
                bind(statement, Int32(index + 1), state.rawValue)
            }
        } row: { statement in
            results.append(Self.job(from: statement))
        }
        return results
    }

    /// `messageID` is only overwritten when non-nil (`COALESCE`), so a caller
    /// that hasn't parsed the file yet (still `pending`) never clobbers a
    /// value a later step already recorded.
    public func updateJobState(sourceID: Int64, messageID: String? = nil, state: DraftJobState,
                               attempts: Int, lastError: String?, updatedAt: Int64) throws {
        lock.lock(); defer { lock.unlock() }
        try run("""
        UPDATE draft_jobs SET
          message_id = COALESCE(?, message_id),
          state = ?, attempts = ?, last_error = ?, updated_at = ?
        WHERE source_id = ?
        """) { statement in
            bindOptional(statement, 1, messageID)
            bind(statement, 2, state.rawValue)
            sqlite3_bind_int64(statement, 3, Int64(attempts))
            bindOptional(statement, 4, lastError)
            sqlite3_bind_int64(statement, 5, updatedAt)
            sqlite3_bind_int64(statement, 6, sourceID)
        }
    }

    /// For a future Settings surfacing (DM-12 status/permission UI), parity
    /// with `SQLiteStore.failedIngestCount`.
    public func pendingAndFailedCounts() throws -> (pending: Int, failed: Int) {
        (try jobCount(state: .pending), try jobCount(state: .failed))
    }

    private func jobCount(state: DraftJobState) throws -> Int {
        lock.lock(); defer { lock.unlock() }
        var result = 0
        try query("SELECT COUNT(*) FROM draft_jobs WHERE state = ?") { statement in
            bind(statement, 1, state.rawValue)
        } row: { statement in
            result = Int(sqlite3_column_int64(statement, 0))
        }
        return result
    }

    /// Deletes terminal job rows older than `cutoff` (Unix seconds):
    /// `drafted`/`newsletterSkipped`/`autoGenerated` outright, and `failed`
    /// rows that have exhausted `maxAttempts` (an automatic retry will never
    /// touch them again, so they're effectively terminal too). Non-terminal
    /// and still-retryable rows are never pruned, however old.
    @discardableResult
    public func pruneJobs(olderThanUnix cutoff: Int64, maxAttempts: Int) throws -> Int {
        lock.lock(); defer { lock.unlock() }
        try run("""
        DELETE FROM draft_jobs WHERE updated_at < ? AND (
          state IN ('drafted', 'newsletter_skipped', 'auto_generated') OR
          (state = 'failed' AND attempts >= ?)
        )
        """) { statement in
            sqlite3_bind_int64(statement, 1, cutoff)
            sqlite3_bind_int(statement, 2, Int32(maxAttempts))
        }
        return Int(sqlite3_changes(db))
    }

    /// Deletes `drafts` rows older than `cutoff` (Unix seconds) — the 14-day
    /// retention policy.
    @discardableResult
    public func pruneDrafts(olderThanUnix cutoff: Int64) throws -> Int {
        lock.lock(); defer { lock.unlock() }
        try run("DELETE FROM drafts WHERE generated_at < ?") { statement in
            sqlite3_bind_int64(statement, 1, cutoff)
        }
        return Int(sqlite3_changes(db))
    }

    private static func job(from statement: OpaquePointer) -> DraftJob {
        DraftJob(
            sourceID: sqlite3_column_int64(statement, 0),
            messageID: sqlite3_column_text(statement, 1).map { String(cString: $0) },
            state: DraftJobState(rawValue: String(cString: sqlite3_column_text(statement, 2))) ?? .pending,
            attempts: Int(sqlite3_column_int64(statement, 3)),
            lastError: sqlite3_column_text(statement, 4).map { String(cString: $0) },
            detectedAt: sqlite3_column_int64(statement, 5),
            updatedAt: sqlite3_column_int64(statement, 6)
        )
    }

    // MARK: Meta (watermark + last-purge timestamps)

    public func meta(_ key: String) throws -> String? {
        lock.lock(); defer { lock.unlock() }
        var value: String?
        try query("SELECT value FROM meta WHERE key = ?") { statement in
            bind(statement, 1, key)
        } row: { statement in
            value = column(statement, 0)
        }
        return value
    }

    public func setMeta(_ key: String, value: String) throws {
        lock.lock(); defer { lock.unlock() }
        try run("INSERT INTO meta(key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value") { statement in
            bind(statement, 1, key)
            bind(statement, 2, value)
        }
    }

    // MARK: SQLite plumbing (mirrors SQLiteStore.swift)

    private func execute(_ sql: String) throws {
        var errorMessage: UnsafeMutablePointer<CChar>?
        guard sqlite3_exec(db, sql, nil, nil, &errorMessage) == SQLITE_OK else {
            let message = errorMessage.map { String(cString: $0) } ?? "unknown"
            sqlite3_free(errorMessage)
            throw StoreError.sql(message)
        }
    }

    private func run(_ sql: String, bind bindings: (OpaquePointer) -> Void) throws {
        var statement: OpaquePointer?
        guard sqlite3_prepare_v2(db, sql, -1, &statement, nil) == SQLITE_OK, let prepared = statement else {
            throw StoreError.sql(String(cString: sqlite3_errmsg(db)))
        }
        defer { sqlite3_finalize(prepared) }
        bindings(prepared)
        guard sqlite3_step(prepared) == SQLITE_DONE else {
            throw StoreError.sql(String(cString: sqlite3_errmsg(db)))
        }
    }

    private func query(_ sql: String,
                       bind bindings: (OpaquePointer) -> Void,
                       row: (OpaquePointer) -> Void) throws {
        var statement: OpaquePointer?
        guard sqlite3_prepare_v2(db, sql, -1, &statement, nil) == SQLITE_OK, let prepared = statement else {
            throw StoreError.sql(String(cString: sqlite3_errmsg(db)))
        }
        defer { sqlite3_finalize(prepared) }
        bindings(prepared)
        while true {
            let status = sqlite3_step(prepared)
            if status == SQLITE_ROW {
                row(prepared)
            } else if status == SQLITE_DONE {
                break
            } else {
                throw StoreError.sql(String(cString: sqlite3_errmsg(db)))
            }
        }
    }

    private func bind(_ statement: OpaquePointer, _ index: Int32, _ value: String) {
        sqlite3_bind_text(statement, index, value, -1, SQLITE_TRANSIENT)
    }

    private func bindOptional(_ statement: OpaquePointer, _ index: Int32, _ value: String?) {
        if let value {
            bind(statement, index, value)
        } else {
            sqlite3_bind_null(statement, index)
        }
    }

    private func column(_ statement: OpaquePointer, _ index: Int32) -> String {
        guard let text = sqlite3_column_text(statement, index) else { return "" }
        return String(cString: text)
    }
}
