import Foundation
import SQLite3

/// Where a drafted reply currently stands.
public enum DraftStatus: String, Sendable, Codable {
    case pending
    case drafting
    case ready
    case failed
    case skippedNewsletter = "skipped_newsletter"
}

/// Where a detected candidate message stands in the Draft-Modus pipeline —
/// the `draft_jobs` table's `state` column. `pending` -> `classifying` ->
/// {`newsletterSkipped` | `autoGenerated` (terminal) | `eligible`} ->
/// `drafting` -> {`drafted` (terminal) | `failed` (retryable with backoff)}.
public enum DraftJobState: String, Sendable, Codable, Equatable {
    case pending
    case classifying
    /// Terminal: `NewsletterClassifier.classify` returned `.newsletter`.
    case newsletterSkipped = "newsletter_skipped"
    /// Terminal: `NewsletterClassifier.isAutoGenerated` matched (RFC 3834
    /// anti-mail-loop gate) — a distinct bucket from `newsletterSkipped` so
    /// Settings can show *why* a message never got a draft.
    case autoGenerated = "auto_generated"
    case eligible
    case drafting
    /// Terminal: a draft was generated and stored.
    case drafted
    /// Retryable: classification or drafting failed (transient LLM error,
    /// vanished source file, empty draft, ...). Eligible for backoff-gated
    /// retry until `attempts` reaches the configured maximum, at which point
    /// it becomes effectively terminal (see `DraftStore.pruneJobs`).
    case failed
}

/// One row of the Draft-Modus job queue (`draft_jobs`).
public struct DraftJob: Sendable, Equatable {
    public var sourceID: Int64
    /// Set once classification has parsed the source file; nil while still
    /// `pending` (the fast envelope-index check doesn't parse the file).
    public var messageID: String?
    public var state: DraftJobState
    public var attempts: Int
    public var lastError: String?
    /// Unix seconds when this candidate was first detected — the SLA clock start.
    public var detectedAt: Int64
    public var updatedAt: Int64

    public init(sourceID: Int64, messageID: String?, state: DraftJobState, attempts: Int,
               lastError: String?, detectedAt: Int64, updatedAt: Int64) {
        self.sourceID = sourceID
        self.messageID = messageID
        self.state = state
        self.attempts = attempts
        self.lastError = lastError
        self.detectedAt = detectedAt
        self.updatedAt = updatedAt
    }
}

public struct DraftRecord: Sendable, Equatable {
    public var pk: Int64
    public var threadID: String
    public var latestMessageID: String
    public var sender: String
    public var subject: String
    public var draftText: String
    public var generatedAt: Int64
    public var status: DraftStatus

    public init(pk: Int64, threadID: String, latestMessageID: String, sender: String, subject: String,
               draftText: String, generatedAt: Int64, status: DraftStatus) {
        self.pk = pk
        self.threadID = threadID
        self.latestMessageID = latestMessageID
        self.sender = sender
        self.subject = subject
        self.draftText = draftText
        self.generatedAt = generatedAt
        self.status = status
    }
}

/// One row of `style_profiles` — a `StyleLearner`-maintained, incrementally
/// merged summary of how the user actually writes, at a given scope (see
/// `StyleScope`).
public struct StyleProfile: Sendable, Equatable {
    public var scope: String
    public var profileText: String
    public var sampleCount: Int
    public var updatedAt: Int64

    public init(scope: String, profileText: String, sampleCount: Int, updatedAt: Int64) {
        self.scope = scope
        self.profileText = profileText
        self.sampleCount = sampleCount
        self.updatedAt = updatedAt
    }
}

private let SQLITE_TRANSIENT = unsafeBitCast(-1, to: sqlite3_destructor_type.self)

/// The local database for Draft-Modus (`drafts.db`), physically decoupled
/// from `askmail.db` (`SQLiteStore`): deleting or rebuilding one never
/// touches the other, and drafted content is never commingled with the
/// read-only mail index. Locked down the same way (`FileHardening`).
///
/// `draft_jobs` and `style_profiles` are schema-only in Phase 1 — a later
/// phase's `DraftEngine`/`StyleLearner` are their only writers.
/// `@unchecked Sendable`: every public method serializes on `lock`; the raw
/// `db` handle is never exposed.
public final class DraftStore: @unchecked Sendable {
    private let db: OpaquePointer
    private let lock = NSLock()

    public init(path: String) throws {
        var handle: OpaquePointer?
        guard sqlite3_open(path, &handle) == SQLITE_OK, let opened = handle else {
            let message = handle.map { String(cString: sqlite3_errmsg($0)) } ?? "unknown"
            if let h = handle { sqlite3_close(h) }
            throw StoreError.openFailed(message)
        }
        db = opened
        try execute("PRAGMA journal_mode=WAL")
        try execute("PRAGMA busy_timeout=5000")
        try migrate()
        if path != ":memory:" {
            FileHardening.lockDown(fileURL: URL(fileURLWithPath: path))
        }
    }

    public static func inMemory() throws -> DraftStore {
        try DraftStore(path: ":memory:")
    }

    deinit {
        sqlite3_close(db)
    }

    // MARK: Schema

    private func migrate() throws {
        try execute("""
        CREATE TABLE IF NOT EXISTS drafts(
          pk INTEGER PRIMARY KEY,
          thread_id TEXT NOT NULL,
          latest_message_id TEXT NOT NULL,
          sender TEXT NOT NULL,
          subject TEXT NOT NULL,
          draft_text TEXT NOT NULL,
          generated_at INTEGER NOT NULL,
          status TEXT NOT NULL
        );
        """)
        // Style learning (Phase 3). NULL means "not yet checked or no match
        // found yet" -- StyleLearner re-examines every such row on each due
        // tick; a row naturally stops being examined once DraftJobProcessor's
        // 14-day retention purge deletes it, so no separate give-up bookkeeping
        // is needed.
        if !(try columnExists("drafts", "style_learned_at")) {
            try execute("ALTER TABLE drafts ADD COLUMN style_learned_at INTEGER")
        }
        try execute("CREATE INDEX IF NOT EXISTS idx_drafts_thread ON drafts(thread_id);")
        try execute("""
        CREATE TABLE IF NOT EXISTS draft_jobs(
          source_id INTEGER PRIMARY KEY,
          message_id TEXT,
          state TEXT NOT NULL,
          attempts INTEGER NOT NULL DEFAULT 0,
          last_error TEXT,
          detected_at INTEGER NOT NULL,
          updated_at INTEGER NOT NULL
        );
        """)
        try execute("""
        CREATE TABLE IF NOT EXISTS style_profiles(
          scope TEXT PRIMARY KEY,
          profile_text TEXT NOT NULL,
          sample_count INTEGER NOT NULL,
          updated_at INTEGER NOT NULL
        );
        """)
        try execute("""
        CREATE TABLE IF NOT EXISTS meta(
          key TEXT PRIMARY KEY,
          value TEXT NOT NULL
        );
        """)
    }

    // MARK: Drafts

    @discardableResult
    public func insertDraft(threadID: String, latestMessageID: String, sender: String, subject: String,
                            draftText: String, generatedAt: Int64, status: DraftStatus) throws -> Int64 {
        lock.lock(); defer { lock.unlock() }
        try run("""
        INSERT INTO drafts(thread_id, latest_message_id, sender, subject, draft_text, generated_at, status)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """) { statement in
            bind(statement, 1, threadID)
            bind(statement, 2, latestMessageID)
            bind(statement, 3, sender)
            bind(statement, 4, subject)
            bind(statement, 5, draftText)
            sqlite3_bind_int64(statement, 6, generatedAt)
            bind(statement, 7, status.rawValue)
        }
        return sqlite3_last_insert_rowid(db)
    }

    /// The most recently generated draft for a thread, if any (a thread may
    /// have several rows if the user regenerated — a later phase's concern).
    public func latestDraft(threadID: String) throws -> DraftRecord? {
        lock.lock(); defer { lock.unlock() }
        var result: DraftRecord?
        try query("""
        SELECT pk, thread_id, latest_message_id, sender, subject, draft_text, generated_at, status
        FROM drafts WHERE thread_id = ? ORDER BY generated_at DESC LIMIT 1
        """) { statement in
            bind(statement, 1, threadID)
        } row: { statement in
            result = DraftRecord(
                pk: sqlite3_column_int64(statement, 0),
                threadID: column(statement, 1),
                latestMessageID: column(statement, 2),
                sender: column(statement, 3),
                subject: column(statement, 4),
                draftText: column(statement, 5),
                generatedAt: sqlite3_column_int64(statement, 6),
                status: DraftStatus(rawValue: column(statement, 7)) ?? .pending
            )
        }
        return result
    }

    // MARK: Drafts surfacing (Phase 4, docs/draft-modus-plan.md)

    /// Ready drafts, newest-first -- backs the read-only Drafts window
    /// (recipient/subject/date/body, never auto-sent or auto-inserted per
    /// `docs/draft-contract.md`). `limit` bounds a pathological backlog from
    /// rendering an unbounded list.
    public func readyDrafts(limit: Int = 200) throws -> [DraftRecord] {
        lock.lock(); defer { lock.unlock() }
        var results: [DraftRecord] = []
        try query("""
        SELECT pk, thread_id, latest_message_id, sender, subject, draft_text, generated_at, status
        FROM drafts WHERE status = 'ready' ORDER BY generated_at DESC LIMIT ?
        """) { statement in
            sqlite3_bind_int(statement, 1, Int32(limit))
        } row: { statement in
            results.append(DraftRecord(
                pk: sqlite3_column_int64(statement, 0),
                threadID: column(statement, 1),
                latestMessageID: column(statement, 2),
                sender: column(statement, 3),
                subject: column(statement, 4),
                draftText: column(statement, 5),
                generatedAt: sqlite3_column_int64(statement, 6),
                status: DraftStatus(rawValue: column(statement, 7)) ?? .pending
            ))
        }
        return results
    }

    /// Ready drafts generated after a previous notification cursor
    /// (exclusive, oldest-first) -- lets `DraftEngine` notify exactly once
    /// per newly-ready draft instead of re-scanning `status = 'ready'` and
    /// guessing which ones are new.
    public func readyDrafts(sincePk cursor: Int64) throws -> [DraftRecord] {
        lock.lock(); defer { lock.unlock() }
        var results: [DraftRecord] = []
        try query("""
        SELECT pk, thread_id, latest_message_id, sender, subject, draft_text, generated_at, status
        FROM drafts WHERE status = 'ready' AND pk > ? ORDER BY pk ASC
        """) { statement in
            sqlite3_bind_int64(statement, 1, cursor)
        } row: { statement in
            results.append(DraftRecord(
                pk: sqlite3_column_int64(statement, 0),
                threadID: column(statement, 1),
                latestMessageID: column(statement, 2),
                sender: column(statement, 3),
                subject: column(statement, 4),
                draftText: column(statement, 5),
                generatedAt: sqlite3_column_int64(statement, 6),
                status: DraftStatus(rawValue: column(statement, 7)) ?? .pending
            ))
        }
        return results
    }

    /// The highest `pk` among `ready` drafts, or 0 if there are none --
    /// bootstraps the notification cursor above so enabling Draft-Modus (or
    /// upgrading into this phase) with pre-existing ready rows doesn't
    /// notify for all of them retroactively in one burst.
    public func maxReadyDraftPk() throws -> Int64 {
        lock.lock(); defer { lock.unlock() }
        var result: Int64 = 0
        try query("SELECT COALESCE(MAX(pk), 0) FROM drafts WHERE status = 'ready'") { _ in
        } row: { statement in
            result = sqlite3_column_int64(statement, 0)
        }
        return result
    }

    /// Count of `ready` drafts -- the menu bar "Drafts (n)" badge and
    /// Settings' "Drafted" status figure (DM-12 surfacing, extended to this
    /// phase's actual output).
    public func readyDraftCount() throws -> Int {
        lock.lock(); defer { lock.unlock() }
        var result = 0
        try query("SELECT COUNT(*) FROM drafts WHERE status = 'ready'") { _ in
        } row: { statement in
            result = Int(sqlite3_column_int64(statement, 0))
        }
        return result
    }

    /// Deletes one draft row (the Drafts window's "Discard" action). This is
    /// the only way a `drafts` row leaves the database before the 14-day
    /// retention purge -- read-only surfacing never writes back to Apple
    /// Mail, so discarding here only ever forgets AskMail's own local copy.
    @discardableResult
    public func deleteDraft(pk: Int64) throws -> Bool {
        lock.lock(); defer { lock.unlock() }
        try run("DELETE FROM drafts WHERE pk = ?") { statement in
            sqlite3_bind_int64(statement, 1, pk)
        }
        return sqlite3_changes(db) > 0
    }

    /// Deletes every `ready` draft for `threadID` -- used by "Regenerate"
    /// (Phase 4, docs/draft-modus-plan.md) so only the freshly generated
    /// draft remains `ready` for that thread, instead of accumulating stale
    /// duplicates. Anticipated since Phase 1: `latestDraft`'s own doc
    /// comment already noted "a thread may have several rows if the user
    /// regenerated — a later phase's concern."
    @discardableResult
    public func deleteReadyDrafts(threadID: String) throws -> Int {
        lock.lock(); defer { lock.unlock() }
        try run("DELETE FROM drafts WHERE thread_id = ? AND status = 'ready'") { statement in
            bind(statement, 1, threadID)
        }
        return Int(sqlite3_changes(db))
    }

    // MARK: Style learning (Phase 3, docs/style-learning-contract.md)

    /// Draft rows `StyleLearner` hasn't yet learned from (`style_learned_at
    /// IS NULL`), old enough to plausibly have a real Sent reply by now,
    /// oldest-generated first so the longest-waiting candidates are examined
    /// before newer ones. `limit` bounds how much local-LLM work one learning
    /// pass performs.
    public func draftsAwaitingStyleLearning(olderThanGeneratedAt cutoff: Int64, limit: Int) throws -> [DraftRecord] {
        lock.lock(); defer { lock.unlock() }
        var results: [DraftRecord] = []
        try query("""
        SELECT pk, thread_id, latest_message_id, sender, subject, draft_text, generated_at, status
        FROM drafts WHERE style_learned_at IS NULL AND generated_at <= ?
        ORDER BY generated_at ASC LIMIT ?
        """) { statement in
            sqlite3_bind_int64(statement, 1, cutoff)
            sqlite3_bind_int(statement, 2, Int32(limit))
        } row: { statement in
            results.append(DraftRecord(
                pk: sqlite3_column_int64(statement, 0),
                threadID: column(statement, 1),
                latestMessageID: column(statement, 2),
                sender: column(statement, 3),
                subject: column(statement, 4),
                draftText: column(statement, 5),
                generatedAt: sqlite3_column_int64(statement, 6),
                status: DraftStatus(rawValue: column(statement, 7)) ?? .pending
            ))
        }
        return results
    }

    /// Marks a draft row as examined so it is never re-considered by a later
    /// learning pass, whether or not a matching Sent reply was actually found
    /// (`StyleLearner` only calls this once it found a match and folded it
    /// into at least one scope's profile — see its doc comment for why a
    /// no-match draft is deliberately left unmarked instead).
    public func markStyleLearned(pk: Int64, at: Int64) throws {
        lock.lock(); defer { lock.unlock() }
        try run("UPDATE drafts SET style_learned_at = ? WHERE pk = ?") { statement in
            sqlite3_bind_int64(statement, 1, at)
            sqlite3_bind_int64(statement, 2, pk)
        }
    }

    /// The learned style profile at a scope (`StyleScope.global`, `.domain`,
    /// or `.address`), if any sample has been folded in yet.
    public func styleProfile(scope: String) throws -> StyleProfile? {
        lock.lock(); defer { lock.unlock() }
        var result: StyleProfile?
        try query("SELECT scope, profile_text, sample_count, updated_at FROM style_profiles WHERE scope = ?") { statement in
            bind(statement, 1, scope)
        } row: { statement in
            result = StyleProfile(scope: column(statement, 0), profileText: column(statement, 1),
                                  sampleCount: Int(sqlite3_column_int64(statement, 2)),
                                  updatedAt: sqlite3_column_int64(statement, 3))
        }
        return result
    }

    /// Every learned style profile, most-recently-updated first — Settings'
    /// transparency surfacing (Phase 6, docs/draft-modus-plan.md): "what
    /// shaped this draft's tone", mirroring the same principle Q&A citations
    /// already give the user.
    public func allStyleProfiles() throws -> [StyleProfile] {
        lock.lock(); defer { lock.unlock() }
        var results: [StyleProfile] = []
        try query("""
        SELECT scope, profile_text, sample_count, updated_at FROM style_profiles ORDER BY updated_at DESC
        """) { _ in
        } row: { statement in
            results.append(StyleProfile(scope: column(statement, 0), profileText: column(statement, 1),
                                        sampleCount: Int(sqlite3_column_int64(statement, 2)),
                                        updatedAt: sqlite3_column_int64(statement, 3)))
        }
        return results
    }

    private static let styleProfilesEpochKey = "style_profiles_epoch"

    /// Monotonic counter bumped by every `deleteStyleProfiles` call. Lets a
    /// caller with a long-running read-modify-write against `style_profiles`
    /// (`StyleLearner.learn`'s multi-second-to-minutes LLM merge calls)
    /// detect that a reset happened *during* that window and discard its
    /// now-stale write, instead of silently resurrecting data the user just
    /// cleared.
    public func styleProfilesEpoch() throws -> Int64 {
        lock.lock(); defer { lock.unlock() }
        return Int64(try rawMeta(Self.styleProfilesEpochKey) ?? "0") ?? 0
    }

    /// Deletes learned style profiles -- Settings' "Reset learned style"
    /// action (Phase 6), mirroring `SQLiteStore.deleteAll()`/FR-8's "delete
    /// & rebuild" pattern but scoped to just `style_profiles`, so a user
    /// unhappy with the learned tone isn't forced into rebuilding the whole
    /// drafts database. `scope` nil deletes every row; otherwise only that
    /// one scope. Does not touch `drafts.style_learned_at` -- already-
    /// examined draft rows stay examined (their evidence was already
    /// folded in and is now gone), so the profile stays empty until *new*
    /// Sent replies are learned from, matching the Phase 6 DoD exactly.
    /// Always bumps `styleProfilesEpoch`, even for a scoped delete or a
    /// delete that matched zero rows -- any reset must be able to
    /// invalidate an in-flight learner write regardless of which scope(s)
    /// that write targets.
    @discardableResult
    public func deleteStyleProfiles(scope: String? = nil) throws -> Int {
        lock.lock(); defer { lock.unlock() }
        if let scope {
            try run("DELETE FROM style_profiles WHERE scope = ?") { statement in
                bind(statement, 1, scope)
            }
        } else {
            try execute("DELETE FROM style_profiles")
        }
        let changed = Int(sqlite3_changes(db))
        let newEpoch = (Int64(try rawMeta(Self.styleProfilesEpochKey) ?? "0") ?? 0) + 1
        try rawSetMeta(Self.styleProfilesEpochKey, value: String(newEpoch))
        return changed
    }

    /// Replaces a scope's profile wholesale — `StyleLearner` always computes
    /// the full new text itself (folding the previous profile in via the
    /// merge prompt), so there is no partial-update case.
    public func upsertStyleProfile(scope: String, profileText: String, sampleCount: Int, updatedAt: Int64) throws {
        lock.lock(); defer { lock.unlock() }
        try run("""
        INSERT INTO style_profiles(scope, profile_text, sample_count, updated_at) VALUES (?, ?, ?, ?)
        ON CONFLICT(scope) DO UPDATE SET
          profile_text = excluded.profile_text, sample_count = excluded.sample_count, updated_at = excluded.updated_at
        """) { statement in
            bind(statement, 1, scope)
            bind(statement, 2, profileText)
            sqlite3_bind_int64(statement, 3, Int64(sampleCount))
            sqlite3_bind_int64(statement, 4, updatedAt)
        }
    }

    // MARK: Job queue (Draft-Modus §7 orchestration)

    /// Enqueues a newly-detected candidate for classification. `INSERT OR
    /// IGNORE` on the `source_id` primary key: a candidate re-detected before
    /// it's been processed (e.g. two overlapping ticks) must never reset an
    /// in-flight job's `state`/`attempts`.
    public func enqueueJob(sourceID: Int64, messageID: String?, detectedAt: Int64) throws {
        lock.lock(); defer { lock.unlock() }
        try run("""
        INSERT OR IGNORE INTO draft_jobs(source_id, message_id, state, attempts, last_error, detected_at, updated_at)
        VALUES (?, ?, 'pending', 0, NULL, ?, ?)
        """) { statement in
            sqlite3_bind_int64(statement, 1, sourceID)
            bindOptional(statement, 2, messageID)
            sqlite3_bind_int64(statement, 3, detectedAt)
            sqlite3_bind_int64(statement, 4, detectedAt)
        }
    }

    public func job(sourceID: Int64) throws -> DraftJob? {
        lock.lock(); defer { lock.unlock() }
        var result: DraftJob?
        try query("""
        SELECT source_id, message_id, state, attempts, last_error, detected_at, updated_at
        FROM draft_jobs WHERE source_id = ?
        """) { statement in
            sqlite3_bind_int64(statement, 1, sourceID)
        } row: { statement in
            result = Self.job(from: statement)
        }
        return result
    }

    /// Jobs in any of `states`, oldest-detected first. Used for both the
    /// `pending` classify queue and the `eligible`/`failed` draft queue.
    public func jobs(in states: [DraftJobState], limit: Int? = nil) throws -> [DraftJob] {
        guard !states.isEmpty else { return [] }
        lock.lock(); defer { lock.unlock() }
        let placeholders = Array(repeating: "?", count: states.count).joined(separator: ",")
        let limitClause = limit.map { " LIMIT \($0)" } ?? ""
        var results: [DraftJob] = []
        try query("""
        SELECT source_id, message_id, state, attempts, last_error, detected_at, updated_at
        FROM draft_jobs WHERE state IN (\(placeholders)) ORDER BY detected_at ASC\(limitClause)
        """) { statement in
            for (index, state) in states.enumerated() {
                bind(statement, Int32(index + 1), state.rawValue)
            }
        } row: { statement in
            results.append(Self.job(from: statement))
        }
        return results
    }

    /// `messageID` is only overwritten when non-nil (`COALESCE`), so a caller
    /// that hasn't parsed the file yet (still `pending`) never clobbers a
    /// value a later step already recorded.
    public func updateJobState(sourceID: Int64, messageID: String? = nil, state: DraftJobState,
                               attempts: Int, lastError: String?, updatedAt: Int64) throws {
        lock.lock(); defer { lock.unlock() }
        try run("""
        UPDATE draft_jobs SET
          message_id = COALESCE(?, message_id),
          state = ?, attempts = ?, last_error = ?, updated_at = ?
        WHERE source_id = ?
        """) { statement in
            bindOptional(statement, 1, messageID)
            bind(statement, 2, state.rawValue)
            sqlite3_bind_int64(statement, 3, Int64(attempts))
            bindOptional(statement, 4, lastError)
            sqlite3_bind_int64(statement, 5, updatedAt)
            sqlite3_bind_int64(statement, 6, sourceID)
        }
    }

    /// For a future Settings surfacing (DM-12 status/permission UI), parity
    /// with `SQLiteStore.failedIngestCount`.
    public func pendingAndFailedCounts() throws -> (pending: Int, failed: Int) {
        (try jobCount(state: .pending), try jobCount(state: .failed))
    }

    /// Job rows that will never be drafted -- newsletter/bulk mail
    /// (`newsletterSkipped`) plus RFC 3834 auto-generated mail
    /// (`autoGenerated`) -- combined into one figure for Settings' "Skipped"
    /// status (DM-12/Phase 6 surfacing). `classifyPendingJobs` keeps the two
    /// states distinct internally (so a later UI could explain *why*), but
    /// they share the same user-facing meaning here.
    public func skippedJobCount() throws -> Int {
        lock.lock(); defer { lock.unlock() }
        var result = 0
        try query("SELECT COUNT(*) FROM draft_jobs WHERE state IN ('newsletter_skipped', 'auto_generated')") { _ in
        } row: { statement in
            result = Int(sqlite3_column_int64(statement, 0))
        }
        return result
    }

    private func jobCount(state: DraftJobState) throws -> Int {
        lock.lock(); defer { lock.unlock() }
        var result = 0
        try query("SELECT COUNT(*) FROM draft_jobs WHERE state = ?") { statement in
            bind(statement, 1, state.rawValue)
        } row: { statement in
            result = Int(sqlite3_column_int64(statement, 0))
        }
        return result
    }

    /// Deletes terminal job rows older than `cutoff` (Unix seconds):
    /// `drafted`/`newsletterSkipped`/`autoGenerated` outright, and `failed`
    /// rows that have exhausted `maxAttempts` (an automatic retry will never
    /// touch them again, so they're effectively terminal too). Non-terminal
    /// and still-retryable rows are never pruned, however old.
    @discardableResult
    public func pruneJobs(olderThanUnix cutoff: Int64, maxAttempts: Int) throws -> Int {
        lock.lock(); defer { lock.unlock() }
        try run("""
        DELETE FROM draft_jobs WHERE updated_at < ? AND (
          state IN ('drafted', 'newsletter_skipped', 'auto_generated') OR
          (state = 'failed' AND attempts >= ?)
        )
        """) { statement in
            sqlite3_bind_int64(statement, 1, cutoff)
            sqlite3_bind_int(statement, 2, Int32(maxAttempts))
        }
        return Int(sqlite3_changes(db))
    }

    /// Deletes `drafts` rows older than `cutoff` (Unix seconds) — the 14-day
    /// retention policy.
    @discardableResult
    public func pruneDrafts(olderThanUnix cutoff: Int64) throws -> Int {
        lock.lock(); defer { lock.unlock() }
        try run("DELETE FROM drafts WHERE generated_at < ?") { statement in
            sqlite3_bind_int64(statement, 1, cutoff)
        }
        return Int(sqlite3_changes(db))
    }

    private static func job(from statement: OpaquePointer) -> DraftJob {
        DraftJob(
            sourceID: sqlite3_column_int64(statement, 0),
            messageID: sqlite3_column_text(statement, 1).map { String(cString: $0) },
            state: DraftJobState(rawValue: String(cString: sqlite3_column_text(statement, 2))) ?? .pending,
            attempts: Int(sqlite3_column_int64(statement, 3)),
            lastError: sqlite3_column_text(statement, 4).map { String(cString: $0) },
            detectedAt: sqlite3_column_int64(statement, 5),
            updatedAt: sqlite3_column_int64(statement, 6)
        )
    }

    // MARK: Meta (watermark + last-purge timestamps)

    public func meta(_ key: String) throws -> String? {
        lock.lock(); defer { lock.unlock() }
        return try rawMeta(key)
    }

    public func setMeta(_ key: String, value: String) throws {
        lock.lock(); defer { lock.unlock() }
        try rawSetMeta(key, value: value)
    }

    /// Lock-free versions of the two above, for callers that already hold
    /// `lock` (`NSLock` isn't reentrant, so `deleteStyleProfiles` needs
    /// these rather than calling back into `meta`/`setMeta`).
    private func rawMeta(_ key: String) throws -> String? {
        var value: String?
        try query("SELECT value FROM meta WHERE key = ?") { statement in
            bind(statement, 1, key)
        } row: { statement in
            value = column(statement, 0)
        }
        return value
    }

    private func rawSetMeta(_ key: String, value: String) throws {
        try run("INSERT INTO meta(key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value") { statement in
            bind(statement, 1, key)
            bind(statement, 2, value)
        }
    }

    // MARK: SQLite plumbing (mirrors SQLiteStore.swift)

    private func execute(_ sql: String) throws {
        var errorMessage: UnsafeMutablePointer<CChar>?
        guard sqlite3_exec(db, sql, nil, nil, &errorMessage) == SQLITE_OK else {
            let message = errorMessage.map { String(cString: $0) } ?? "unknown"
            sqlite3_free(errorMessage)
            throw StoreError.sql(message)
        }
    }

    private func run(_ sql: String, bind bindings: (OpaquePointer) -> Void) throws {
        var statement: OpaquePointer?
        guard sqlite3_prepare_v2(db, sql, -1, &statement, nil) == SQLITE_OK, let prepared = statement else {
            throw StoreError.sql(String(cString: sqlite3_errmsg(db)))
        }
        defer { sqlite3_finalize(prepared) }
        bindings(prepared)
        guard sqlite3_step(prepared) == SQLITE_DONE else {
            throw StoreError.sql(String(cString: sqlite3_errmsg(db)))
        }
    }

    private func query(_ sql: String,
                       bind bindings: (OpaquePointer) -> Void,
                       row: (OpaquePointer) -> Void) throws {
        var statement: OpaquePointer?
        guard sqlite3_prepare_v2(db, sql, -1, &statement, nil) == SQLITE_OK, let prepared = statement else {
            throw StoreError.sql(String(cString: sqlite3_errmsg(db)))
        }
        defer { sqlite3_finalize(prepared) }
        bindings(prepared)
        while true {
            let status = sqlite3_step(prepared)
            if status == SQLITE_ROW {
                row(prepared)
            } else if status == SQLITE_DONE {
                break
            } else {
                throw StoreError.sql(String(cString: sqlite3_errmsg(db)))
            }
        }
    }

    private func bind(_ statement: OpaquePointer, _ index: Int32, _ value: String) {
        sqlite3_bind_text(statement, index, value, -1, SQLITE_TRANSIENT)
    }

    private func bindOptional(_ statement: OpaquePointer, _ index: Int32, _ value: String?) {
        if let value {
            bind(statement, index, value)
        } else {
            sqlite3_bind_null(statement, index)
        }
    }

    private func column(_ statement: OpaquePointer, _ index: Int32) -> String {
        guard let text = sqlite3_column_text(statement, index) else { return "" }
        return String(cString: text)
    }

    private func columnExists(_ table: String, _ column: String) throws -> Bool {
        var exists = false
        try query("PRAGMA table_info(\(table))") { _ in } row: { statement in
            if String(cString: sqlite3_column_text(statement, 1)) == column {
                exists = true
            }
        }
        return exists
    }
}
