import Foundation

/// Decides whether an incoming message is a newsletter/bulk mail (skip
/// drafting) or personal correspondence (draft it). Two hard gates —
/// `isAutoGenerated` (RFC 3834 anti-mail-loop) and `isNoReplySender`
/// (`noreply@`/`no-reply@`) — are checked by the caller *before* this is
/// ever invoked, exactly like each other; `classify` is the correspondence
/// heuristic for whatever survives both. A user-configurable sender
/// exclusion list remains an unimplemented, later-phase Settings feature —
/// this type has no `SettingsStore` dependency and stays fully
/// unit-testable against plain headers/strings.
public enum NewsletterClassifier {

    public enum Verdict: Equatable {
        case newsletter(reason: String)
        case personal(reason: String)
        case ambiguous
    }

    /// Reconstructs the generic header pairs `classify`/`isAutoGenerated`
    /// expect from an already-ingested `IngestableEmail`'s named fields —
    /// `IngestableEmail` deliberately carries only these specific fields
    /// (hardening DM-6: string-only across the XPC boundary), not a raw
    /// header list, so any caller classifying post-parse needs this same
    /// small adapter.
    public static func headers(from email: IngestableEmail) -> [(String, String)] {
        [
            ("List-Unsubscribe", email.listUnsubscribe ?? ""),
            ("List-Id", email.listId ?? ""),
            ("Precedence", email.precedence ?? ""),
            ("Auto-Submitted", email.autoSubmitted ?? ""),
        ]
    }

    /// RFC 3834 anti-mail-loop gate, checked by the caller *before*
    /// `classify` and independent of newsletter status: a background
    /// auto-drafter must never reply to another system's autoresponder.
    public static func isAutoGenerated(headers: [(String, String)]) -> Bool {
        guard let value = header(headers, "Auto-Submitted") else { return false }
        let normalized = value.trimmingCharacters(in: .whitespaces).lowercased()
        return normalized == "auto-generated" || normalized == "auto-replied"
    }

    /// Hard "never reply" rule, checked by the caller *before* `classify`,
    /// exactly like `isAutoGenerated`: a `noreply@`/`no-reply@` sender has
    /// nobody listening on the other end, so a drafted reply is pointless
    /// regardless of whether the message otherwise looks personal — this is
    /// a certainty, not a heuristic that needs corroboration from a second
    /// weak signal or an LLM fallback, so it does not go through
    /// `classify`'s weak-signal path at all.
    private static let noReplyLocalParts = ["noreply", "no-reply"]

    public static func isNoReplySender(_ sender: String) -> Bool {
        guard let part = localPart(of: sender) else { return false }
        return noReplyLocalParts.contains { part.hasPrefix($0) }
    }

    /// Order: strong header signals (`List-Unsubscribe`/`List-Id`/
    /// `Precedence: bulk|list|junk`) decide alone. Otherwise, a weak sender
    /// local-part pattern and a weak boilerplate tie-break
    /// (`HtmlText.stripBoilerplate`) are combined — either alone is
    /// `ambiguous` (falls back to `llmFallback`, an always-local `OllamaClient`
    /// per the caller); both together decide `newsletter`. No signal at all
    /// decides `personal`.
    public static func classify(headers: [(String, String)], sender: String, bodyText: String,
                                hasPriorSentCorrespondence: Bool,
                                llmFallback: ChatProvider?) async -> Verdict {
        if hasPriorSentCorrespondence {
            return .personal(reason: "prior Sent correspondence with this address")
        }
        if let reason = strongSignal(headers: headers) {
            return .newsletter(reason: reason)
        }

        let weakSenderMatch = matchesNewsletterLocalPart(sender)
        let boilerplateDetected = HtmlText.stripBoilerplate(bodyText).count < bodyText.count

        if weakSenderMatch, boilerplateDetected {
            return .newsletter(reason: "sender local-part pattern + unsubscribe-language boilerplate")
        }
        if weakSenderMatch || boilerplateDetected {
            guard let llmFallback else { return .ambiguous }
            return await llmVerdict(sender: sender, bodyText: bodyText, provider: llmFallback)
        }
        return .personal(reason: "no newsletter signals detected")
    }

    // MARK: Strong signals

    private static func strongSignal(headers: [(String, String)]) -> String? {
        if let listUnsubscribe = header(headers, "List-Unsubscribe"),
           !listUnsubscribe.trimmingCharacters(in: .whitespaces).isEmpty {
            return "List-Unsubscribe present"
        }
        if let listId = header(headers, "List-Id"),
           !listId.trimmingCharacters(in: .whitespaces).isEmpty {
            return "List-Id present"
        }
        if let precedence = header(headers, "Precedence")?.trimmingCharacters(in: .whitespaces).lowercased(),
           ["bulk", "list", "junk"].contains(precedence) {
            return "Precedence: \(precedence)"
        }
        return nil
    }

    // MARK: Weak signals

    private static let newsletterLocalParts = ["newsletter", "notifications", "digest", "updates", "bounce"]

    private static func matchesNewsletterLocalPart(_ sender: String) -> Bool {
        guard let localPart = localPart(of: sender) else { return false }
        return newsletterLocalParts.contains { localPart.hasPrefix($0) }
    }

    /// The address local-part (before `@`), lowercased, from a `From`-style
    /// header value that may be `Name <addr@host>` or a bare address.
    static func localPart(of sender: String) -> String? {
        let address: Substring
        if let lt = sender.firstIndex(of: "<"),
           let gt = sender[sender.index(after: lt)...].firstIndex(of: ">") {
            address = sender[sender.index(after: lt)..<gt]
        } else {
            address = sender[...]
        }
        guard let at = address.firstIndex(of: "@") else { return nil }
        return address[address.startIndex..<at].lowercased()
    }

    // MARK: LLM fallback

    private static func llmVerdict(sender: String, bodyText: String, provider: ChatProvider) async -> Verdict {
        let request = ChatRequest(
            system: "You classify one email as either a newsletter/marketing/automated bulk "
                + "message, or a personal message. Reply with exactly one word: "
                + "\"newsletter\" or \"personal\". No other text.",
            user: "From: \(sender)\n\nBody:\n\(String(bodyText.prefix(1000)))",
            maxTokens: 5, temperature: 0)
        var answer = ""
        do {
            for try await token in provider.stream(request) {
                answer += token
            }
        } catch {
            return .ambiguous
        }
        let normalized = answer.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        if normalized.contains("newsletter") { return .newsletter(reason: "local LLM classification") }
        if normalized.contains("personal") { return .personal(reason: "local LLM classification") }
        return .ambiguous
    }

    // MARK: Header lookup

    private static func header(_ headers: [(String, String)], _ name: String) -> String? {
        let lower = name.lowercased()
        return headers.first { $0.0.lowercased() == lower }?.1
    }
}
