import Foundation

/// User-configurable "never draft for this sender/domain" list (Phase 6,
/// docs/draft-modus-plan.md), checked by the caller *before*
/// `NewsletterClassifier` the same way `NewsletterClassifier.isAutoGenerated`/
/// `isNoReplySender` already are -- see `DraftJobProcessor.classifyPendingJobs`.
/// A free function over a plain `[String]`, mirroring `NewsletterClassifier`'s
/// own no-`SettingsStore`-dependency stance, so this stays fully
/// unit-testable; `SettingsStore.draftExcludedSenders` is the one caller
/// that actually populates the list from user input.
public enum SenderExclusion {

    /// True when `sender`'s address or host matches an entry in `excluded`.
    /// Each entry may be a full address (`"spam@bigcorp.com"`) or a bare
    /// domain (`"bigcorp.com"`, matching any address at that host or a
    /// subdomain of it, e.g. `"news.bigcorp.com"`). Comparison is
    /// case-insensitive; blank entries are ignored. A `sender` header with
    /// no parseable address never matches (fails open to "not excluded",
    /// consistent with `NewsletterClassifier.isNoReplySender`'s own
    /// no-address handling).
    public static func isExcluded(_ sender: String, excluded: [String]) -> Bool {
        guard let address = MailHeader.address(fromSender: sender) else { return false }
        let host = String(address.split(separator: "@").last ?? "")
        guard !host.isEmpty else { return false }
        for raw in excluded {
            let entry = raw.trimmingCharacters(in: .whitespaces).lowercased()
            guard !entry.isEmpty else { continue }
            if entry.contains("@") {
                if address == entry { return true }
            } else if host == entry || host.hasSuffix(".\(entry)") {
                return true
            }
        }
        return false
    }
}
