import XCTest
@testable import AskMailCore

final class DraftStoreJobTests: XCTestCase {

    func testEnqueueThenFetchRoundTrips() throws {
        let store = try DraftStore.inMemory()
        try store.enqueueJob(sourceID: 1, messageID: nil, detectedAt: 100)

        let job = try XCTUnwrap(try store.job(sourceID: 1))
        XCTAssertEqual(job.sourceID, 1)
        XCTAssertNil(job.messageID)
        XCTAssertEqual(job.state, .pending)
        XCTAssertEqual(job.attempts, 0)
        XCTAssertNil(job.lastError)
        XCTAssertEqual(job.detectedAt, 100)
        XCTAssertEqual(job.updatedAt, 100)
    }

    func testMissingJobReturnsNil() throws {
        let store = try DraftStore.inMemory()
        XCTAssertNil(try store.job(sourceID: 999))
    }

    func testEnqueueIsIdempotentAndNeverResetsAnInFlightJob() throws {
        let store = try DraftStore.inMemory()
        try store.enqueueJob(sourceID: 1, messageID: nil, detectedAt: 100)
        try store.updateJobState(sourceID: 1, state: .classifying, attempts: 2, lastError: "boom", updatedAt: 200)

        // A re-detection of the same candidate (e.g. two overlapping ticks)
        // must not clobber the in-flight state/attempts.
        try store.enqueueJob(sourceID: 1, messageID: nil, detectedAt: 999)

        let job = try XCTUnwrap(try store.job(sourceID: 1))
        XCTAssertEqual(job.state, .classifying)
        XCTAssertEqual(job.attempts, 2)
        XCTAssertEqual(job.lastError, "boom")
        XCTAssertEqual(job.detectedAt, 100, "original detection time must survive")
    }

    func testJobsInStatesFiltersAndOrdersByDetectedAtAscending() throws {
        let store = try DraftStore.inMemory()
        try store.enqueueJob(sourceID: 3, messageID: nil, detectedAt: 300)
        try store.enqueueJob(sourceID: 1, messageID: nil, detectedAt: 100)
        try store.enqueueJob(sourceID: 2, messageID: nil, detectedAt: 200)
        try store.updateJobState(sourceID: 2, state: .eligible, attempts: 0, lastError: nil, updatedAt: 200)

        let pending = try store.jobs(in: [.pending])
        XCTAssertEqual(pending.map(\.sourceID), [1, 3], "oldest-detected first, eligible excluded")

        let eligible = try store.jobs(in: [.eligible])
        XCTAssertEqual(eligible.map(\.sourceID), [2])

        let both = try store.jobs(in: [.pending, .eligible])
        XCTAssertEqual(both.map(\.sourceID), [1, 2, 3])
    }

    func testJobsRespectsLimit() throws {
        let store = try DraftStore.inMemory()
        for id in 1...5 {
            try store.enqueueJob(sourceID: Int64(id), messageID: nil, detectedAt: Int64(id) * 10)
        }
        let limited = try store.jobs(in: [.pending], limit: 2)
        XCTAssertEqual(limited.map(\.sourceID), [1, 2])
    }

    func testUpdateJobStateSetsMessageIDOnceKnownWithoutClobberingLater() throws {
        let store = try DraftStore.inMemory()
        try store.enqueueJob(sourceID: 1, messageID: nil, detectedAt: 100)

        try store.updateJobState(sourceID: 1, messageID: "abc@x", state: .eligible,
                                 attempts: 0, lastError: nil, updatedAt: 150)
        XCTAssertEqual(try store.job(sourceID: 1)?.messageID, "abc@x")

        // A later update that doesn't know the messageID (nil) must not erase it.
        try store.updateJobState(sourceID: 1, state: .drafting, attempts: 0, lastError: nil, updatedAt: 160)
        XCTAssertEqual(try store.job(sourceID: 1)?.messageID, "abc@x")
    }

    func testPendingAndFailedCounts() throws {
        let store = try DraftStore.inMemory()
        try store.enqueueJob(sourceID: 1, messageID: nil, detectedAt: 1)
        try store.enqueueJob(sourceID: 2, messageID: nil, detectedAt: 2)
        try store.enqueueJob(sourceID: 3, messageID: nil, detectedAt: 3)
        try store.updateJobState(sourceID: 2, state: .failed, attempts: 1, lastError: "x", updatedAt: 2)
        try store.updateJobState(sourceID: 3, state: .drafted, attempts: 0, lastError: nil, updatedAt: 3)

        let counts = try store.pendingAndFailedCounts()
        XCTAssertEqual(counts.pending, 1)
        XCTAssertEqual(counts.failed, 1)
    }

    func testPruneJobsRemovesOldTerminalRowsOnly() throws {
        let store = try DraftStore.inMemory()
        // Old + terminal -> pruned.
        try store.enqueueJob(sourceID: 1, messageID: nil, detectedAt: 1)
        try store.updateJobState(sourceID: 1, state: .drafted, attempts: 0, lastError: nil, updatedAt: 100)
        try store.enqueueJob(sourceID: 2, messageID: nil, detectedAt: 1)
        try store.updateJobState(sourceID: 2, state: .newsletterSkipped, attempts: 0, lastError: nil, updatedAt: 100)
        try store.enqueueJob(sourceID: 3, messageID: nil, detectedAt: 1)
        try store.updateJobState(sourceID: 3, state: .autoGenerated, attempts: 0, lastError: nil, updatedAt: 100)
        // Old + failed at max attempts -> pruned.
        try store.enqueueJob(sourceID: 4, messageID: nil, detectedAt: 1)
        try store.updateJobState(sourceID: 4, state: .failed, attempts: 5, lastError: "x", updatedAt: 100)
        // Old + failed but still retryable -> kept.
        try store.enqueueJob(sourceID: 5, messageID: nil, detectedAt: 1)
        try store.updateJobState(sourceID: 5, state: .failed, attempts: 2, lastError: "x", updatedAt: 100)
        // Old but still in-flight -> kept regardless of age.
        try store.enqueueJob(sourceID: 6, messageID: nil, detectedAt: 1)
        try store.updateJobState(sourceID: 6, state: .eligible, attempts: 0, lastError: nil, updatedAt: 100)
        // Terminal but NOT old enough -> kept.
        try store.enqueueJob(sourceID: 7, messageID: nil, detectedAt: 1)
        try store.updateJobState(sourceID: 7, state: .drafted, attempts: 0, lastError: nil, updatedAt: 900)

        let pruned = try store.pruneJobs(olderThanUnix: 500, maxAttempts: 5)
        XCTAssertEqual(pruned, 4)

        let remainingIDs = Set(try store.jobs(in: DraftJobState.allTestCases).map(\.sourceID))
        XCTAssertEqual(remainingIDs, [5, 6, 7])
    }

    func testPruneDraftsRemovesOlderThanCutoffByGeneratedAt() throws {
        let store = try DraftStore.inMemory()
        try store.insertDraft(threadID: "t1", latestMessageID: "m1", sender: "a@x", subject: "s1",
                              draftText: "old", generatedAt: 100, status: .ready)
        try store.insertDraft(threadID: "t2", latestMessageID: "m2", sender: "a@x", subject: "s2",
                              draftText: "new", generatedAt: 900, status: .ready)

        let pruned = try store.pruneDrafts(olderThanUnix: 500)
        XCTAssertEqual(pruned, 1)
        XCTAssertNil(try store.latestDraft(threadID: "t1"))
        XCTAssertNotNil(try store.latestDraft(threadID: "t2"))
    }

    func testMetaRoundTripsAndOverwrites() throws {
        let store = try DraftStore.inMemory()
        XCTAssertNil(try store.meta("draft_watermark_date_unix"))
        try store.setMeta("draft_watermark_date_unix", value: "123")
        XCTAssertEqual(try store.meta("draft_watermark_date_unix"), "123")
        try store.setMeta("draft_watermark_date_unix", value: "456")
        XCTAssertEqual(try store.meta("draft_watermark_date_unix"), "456")
    }
}

private extension DraftJobState {
    /// All cases, for a test that wants to fetch every job regardless of state.
    static var allTestCases: [DraftJobState] {
        [.pending, .classifying, .newsletterSkipped, .autoGenerated, .eligible, .drafting, .drafted, .failed]
    }
}
