import XCTest
@testable import AskMailCore

final class NewsletterClassifierTests: XCTestCase {

    // MARK: isAutoGenerated (RFC 3834 anti-mail-loop gate)

    func testAutoSubmittedAutoGeneratedIsDetected() {
        XCTAssertTrue(NewsletterClassifier.isAutoGenerated(headers: [("Auto-Submitted", "auto-generated")]))
    }

    func testAutoSubmittedAutoRepliedIsDetected() {
        XCTAssertTrue(NewsletterClassifier.isAutoGenerated(headers: [("Auto-Submitted", "auto-replied")]))
    }

    func testAutoSubmittedNoIsNotDetected() {
        XCTAssertFalse(NewsletterClassifier.isAutoGenerated(headers: [("Auto-Submitted", "no")]))
    }

    func testMissingAutoSubmittedIsNotDetected() {
        XCTAssertFalse(NewsletterClassifier.isAutoGenerated(headers: []))
    }

    // MARK: isNoReplySender (hard "never reply" gate)

    func testBareNoReplyAddressIsDetected() {
        XCTAssertTrue(NewsletterClassifier.isNoReplySender("noreply@example.com"))
    }

    func testHyphenatedNoReplyAddressIsDetected() {
        XCTAssertTrue(NewsletterClassifier.isNoReplySender("no-reply@example.com"))
    }

    func testNoReplyWithDisplayNameIsDetected() {
        XCTAssertTrue(NewsletterClassifier.isNoReplySender("Acme Support <noreply@example.com>"))
    }

    func testNoReplySubaddressVariantIsDetected() {
        XCTAssertTrue(NewsletterClassifier.isNoReplySender("noreply-notifications@example.com"))
    }

    func testCaseInsensitiveNoReplyIsDetected() {
        XCTAssertTrue(NewsletterClassifier.isNoReplySender("NoReply@Example.com"))
    }

    // MARK: isNewsletterAddress (hard "never reply" gate, whole address)

    func testNewsletterInLocalPartIsDetected() {
        XCTAssertTrue(NewsletterClassifier.isNewsletterAddress("newsletter@example.com"))
    }

    func testNewsletterInDomainIsDetected() {
        XCTAssertTrue(NewsletterClassifier.isNewsletterAddress("bafinDE@newsletter.gsb.bund.de"))
    }

    func testNewsletterWithDisplayNameIsDetected() {
        XCTAssertTrue(NewsletterClassifier.isNewsletterAddress("Acme <updates@newsletter.acme.com>"))
    }

    func testCaseInsensitiveNewsletterIsDetected() {
        XCTAssertTrue(NewsletterClassifier.isNewsletterAddress("Info@NEWSLETTER.example.com"))
    }

    func testOrdinaryAddressWithoutNewsletterIsNotDetected() {
        XCTAssertFalse(NewsletterClassifier.isNewsletterAddress("max@example.com"))
    }

    func testUnparseableAddressIsNotDetected() {
        XCTAssertFalse(NewsletterClassifier.isNewsletterAddress("not an address"))
    }

    func testUnrelatedLocalPartResemblingNoReplyIsNotDetected() {
        // "notreply" must not false-positive as a "noreply" prefix match.
        XCTAssertFalse(NewsletterClassifier.isNoReplySender("notreply@example.com"))
    }

    func testOrdinaryPersonalAddressIsNotDetected() {
        XCTAssertFalse(NewsletterClassifier.isNoReplySender("alice@example.com"))
    }

    func testDisplayNameOnlySenderIsNotDetected() {
        XCTAssertFalse(NewsletterClassifier.isNoReplySender("Internal Memo"))
    }

    // MARK: classify — strong signals

    func testListUnsubscribeIsStrongNewsletterSignal() async {
        let verdict = await NewsletterClassifier.classify(
            headers: [("List-Unsubscribe", "<mailto:unsub@example.com>")],
            sender: "team@example.com", bodyText: "Hello there, just a note.",
            hasPriorSentCorrespondence: false, llmFallback: nil)
        guard case .newsletter = verdict else { return XCTFail("expected newsletter, got \(verdict)") }
    }

    func testListIdIsStrongNewsletterSignal() async {
        let verdict = await NewsletterClassifier.classify(
            headers: [("List-Id", "Weekly Digest <digest.example.com>")],
            sender: "team@example.com", bodyText: "Hello there.",
            hasPriorSentCorrespondence: false, llmFallback: nil)
        guard case .newsletter = verdict else { return XCTFail("expected newsletter, got \(verdict)") }
    }

    func testPrecedenceBulkIsStrongNewsletterSignal() async {
        for value in ["bulk", "list", "junk"] {
            let verdict = await NewsletterClassifier.classify(
                headers: [("Precedence", value)],
                sender: "team@example.com", bodyText: "Hello there.",
                hasPriorSentCorrespondence: false, llmFallback: nil)
            guard case .newsletter = verdict else { return XCTFail("Precedence \(value) expected newsletter, got \(verdict)") }
        }
    }

    // MARK: classify — Sent-correspondence override

    func testPriorSentCorrespondenceOverridesEvenStrongNewsletterHeaders() async {
        let verdict = await NewsletterClassifier.classify(
            headers: [("List-Unsubscribe", "<mailto:unsub@example.com>")],
            sender: "colleague@example.com", bodyText: "Hey, following up on our chat.",
            hasPriorSentCorrespondence: true, llmFallback: nil)
        guard case .personal = verdict else { return XCTFail("expected personal, got \(verdict)") }
    }

    // MARK: classify — weak signals combine

    func testWeakSenderPatternAloneIsAmbiguousWithoutLLM() async {
        let verdict = await NewsletterClassifier.classify(
            headers: [], sender: "newsletter@example.com", bodyText: "Some ordinary text, nothing boilerplate.",
            hasPriorSentCorrespondence: false, llmFallback: nil)
        XCTAssertEqual(verdict, .ambiguous)
    }

    func testBoilerplateAloneIsAmbiguousWithoutLLM() async {
        let verdict = await NewsletterClassifier.classify(
            headers: [], sender: "person@example.com",
            bodyText: "Some content.\n\nPlease unsubscribe if you no longer wish to receive these emails.",
            hasPriorSentCorrespondence: false, llmFallback: nil)
        XCTAssertEqual(verdict, .ambiguous)
    }

    func testWeakSenderPatternPlusBoilerplateDecidesNewsletter() async {
        let verdict = await NewsletterClassifier.classify(
            headers: [], sender: "notifications@example.com",
            bodyText: "Some content.\n\nPlease unsubscribe if you no longer wish to receive these emails.",
            hasPriorSentCorrespondence: false, llmFallback: nil)
        guard case .newsletter = verdict else { return XCTFail("expected newsletter, got \(verdict)") }
    }

    func testNoSignalsAtAllIsPersonal() async {
        let verdict = await NewsletterClassifier.classify(
            headers: [], sender: "friend@example.com", bodyText: "Want to grab lunch tomorrow?",
            hasPriorSentCorrespondence: false, llmFallback: nil)
        guard case .personal = verdict else { return XCTFail("expected personal, got \(verdict)") }
    }

    // MARK: classify — ambiguous falls back to the local LLM

    func testAmbiguousCaseUsesLLMFallback() async {
        let stub = StubChatProvider(name: "stub-local", tokens: ["newsletter"])
        let verdict = await NewsletterClassifier.classify(
            headers: [], sender: "updates@example.com", bodyText: "Some ordinary text, nothing boilerplate.",
            hasPriorSentCorrespondence: false, llmFallback: stub)
        guard case .newsletter(let reason) = verdict else { return XCTFail("expected newsletter, got \(verdict)") }
        XCTAssertTrue(reason.contains("LLM"))
    }

    func testAmbiguousLLMFailureStaysAmbiguous() async {
        let stub = StubChatProvider(name: "stub-local", tokens: [], error: ProviderError.malformedResponse("boom"))
        let verdict = await NewsletterClassifier.classify(
            headers: [], sender: "updates@example.com", bodyText: "Some ordinary text, nothing boilerplate.",
            hasPriorSentCorrespondence: false, llmFallback: stub)
        XCTAssertEqual(verdict, .ambiguous)
    }
}
